-- Seed data: supported Dubai areas.
--
-- Safe to re-run: existing areas are left untouched (name is unique per city).
-- Areas are data, not code - add, rename or deactivate them from /admin/areas.

insert into public.areas (name, city, emirate, active, sort_order) values
  ('Al Barsha', 'Dubai', 'Dubai', true, 10),
  ('Al Barsha South', 'Dubai', 'Dubai', true, 20),
  ('Al Furjan', 'Dubai', 'Dubai', true, 30),
  ('Al Garhoud', 'Dubai', 'Dubai', true, 40),
  ('Al Jaddaf', 'Dubai', 'Dubai', true, 50),
  ('Al Karama', 'Dubai', 'Dubai', true, 60),
  ('Al Khail', 'Dubai', 'Dubai', true, 70),
  ('Al Nahda Dubai', 'Dubai', 'Dubai', true, 80),
  ('Al Quoz', 'Dubai', 'Dubai', true, 90),
  ('Al Qusais', 'Dubai', 'Dubai', true, 100),
  ('Al Satwa', 'Dubai', 'Dubai', true, 110),
  ('Arabian Ranches', 'Dubai', 'Dubai', true, 120),
  ('Arjan', 'Dubai', 'Dubai', true, 130),
  ('Barsha Heights', 'Dubai', 'Dubai', true, 140),
  ('Business Bay', 'Dubai', 'Dubai', true, 150),
  ('City Walk', 'Dubai', 'Dubai', true, 160),
  ('Damac Hills', 'Dubai', 'Dubai', true, 170),
  ('Deira', 'Dubai', 'Dubai', true, 180),
  ('Discovery Gardens', 'Dubai', 'Dubai', true, 190),
  ('Downtown Dubai', 'Dubai', 'Dubai', true, 200),
  ('Dubai Creek Harbour', 'Dubai', 'Dubai', true, 210),
  ('Dubai Festival City', 'Dubai', 'Dubai', true, 220),
  ('Dubai Hills', 'Dubai', 'Dubai', true, 230),
  ('Dubai Investment Park', 'Dubai', 'Dubai', true, 240),
  ('Dubai Marina', 'Dubai', 'Dubai', true, 250),
  ('Dubai Production City', 'Dubai', 'Dubai', true, 260),
  ('Dubai Residence Complex', 'Dubai', 'Dubai', true, 270),
  ('Dubai Silicon Oasis', 'Dubai', 'Dubai', true, 280),
  ('Dubai South', 'Dubai', 'Dubai', true, 290),
  ('Dubai Sports City', 'Dubai', 'Dubai', true, 300),
  ('Emirates Hills', 'Dubai', 'Dubai', true, 310),
  ('International City', 'Dubai', 'Dubai', true, 320),
  ('JBR', 'Dubai', 'Dubai', true, 330),
  ('JLT', 'Dubai', 'Dubai', true, 340),
  ('Jumeirah', 'Dubai', 'Dubai', true, 350),
  ('Jumeirah Village Circle', 'Dubai', 'Dubai', true, 360),
  ('Jumeirah Village Triangle', 'Dubai', 'Dubai', true, 370),
  ('Mirdif', 'Dubai', 'Dubai', true, 380),
  ('Motor City', 'Dubai', 'Dubai', true, 390),
  ('Muhaisnah', 'Dubai', 'Dubai', true, 400),
  ('Oud Metha', 'Dubai', 'Dubai', true, 410),
  ('Palm Jumeirah', 'Dubai', 'Dubai', true, 420),
  ('Ras Al Khor', 'Dubai', 'Dubai', true, 430),
  ('Sports City', 'Dubai', 'Dubai', true, 440),
  ('The Greens', 'Dubai', 'Dubai', true, 450),
  ('The Springs', 'Dubai', 'Dubai', true, 460),
  ('Umm Suqeim', 'Dubai', 'Dubai', true, 470)
on conflict (city, name) do nothing;
