import type { ScreenQuad } from "./phone";

/**
 * The generated footage this ad is designed around, and the prompts that produce
 * it.
 *
 * Nothing here is filled in. The ad renders complete without a frame of
 * generated video - every plate falls back to a drawn stand-in - so the cut,
 * the timing and the mix can all be signed off before a credit is spent. That
 * ordering is deliberate: footage commissioned against an approved edit is one
 * generation per shot, and footage commissioned against a description is five.
 *
 * Two of these slots need a human being and cannot be faked by any amount of
 * drawing. Those beats currently lean on the phone and the food, which works,
 * but the ad is materially stronger with a face in it - that is the single
 * highest-value thing to add next.
 */

export type FootagePlate = {
  /** Path under public/, or null to draw the stand-in instead. */
  src: string | null;
  trimBefore?: number;
  trimAfter?: number;
  /** What this shot is for, in the edit. */
  role: string;
  /** The Runway prompt, ready to paste. */
  prompt: string;
  /**
   * Where the phone screen sits in the generated frame, once there is one.
   *
   * Generative video cannot be trusted with a price, a logo or an interface, so
   * whatever it paints on the glass is thrown away: give the four screen corners
   * here and ScreenComposite corner-pins the real UI over them. For a moving
   * shot this becomes a function of the frame - four tracked points per frame -
   * which is the one job in this pipeline that genuinely wants a human with a
   * tracker rather than a prompt.
   */
  screen?: ScreenQuad | null;
};

const NO_TEXT =
  "No readable text anywhere in frame, no on-screen graphics, no logos, no brand names, no subtitles.";

const LOOK =
  "Premium commercial cinematography, shot on a full-frame camera with a fast prime, " +
  "shallow depth of field, natural film grain, warm practical lighting, no colour cast towards teal, " +
  "vertical 9:16 composition framed for mobile.";

/**
 * The hook. A person, at home, seeing what dinner is about to cost.
 *
 * The most valuable three seconds in the ad and the one shot that most needs a
 * real face: the entire premise is an expression.
 */
export const HOOK: FootagePlate = {
  src: null,
  role: "0.0-2.5s. Opening. Over-the-shoulder onto the phone, pushing in.",
  prompt:
    "Night interior, modern Dubai apartment. A young adult in their late twenties sits back on a " +
    "linen sofa holding a smartphone, hungry and browsing a food delivery order. They glance at the " +
    "screen and their face falls slightly - a small, real, unperformed reaction to a number being " +
    "higher than expected. A warm table lamp behind them, cool phone light on their face and hands. " +
    "Slow push in from over the shoulder towards the phone. Realistic hands holding the phone naturally. " +
    `${LOOK} ${NO_TEXT}`,
  screen: null,
};

/**
 * The reaction. Same person, same room, same everything - seconds later.
 *
 * Continuity is the whole job here. Generate this in the same session as the
 * hook, from the same reference frame, or it reads as two different ads.
 */
export const REACTION: FootagePlate = {
  src: null,
  role: "11.5-14.0s. The payoff on a face.",
  prompt:
    "Same young adult, same linen sofa, same modern Dubai apartment at night, same clothes and same " +
    "lighting as the previous shot. They look down at their smartphone and react with quiet, genuine, " +
    "pleased surprise - a small smile and a slight lift of the eyebrows, restrained rather than " +
    "delighted. Warm lamp behind, cool phone light on the face. Subtle handheld camera, very slight " +
    "push in. Realistic hands and phone. " +
    `${LOOK} ${NO_TEXT}`,
  screen: null,
};

/**
 * The food. The one shot with no continuity burden and the easiest to generate
 * well, which is why it is also the safest place to spend the first credit.
 */
export const FOOD: FootagePlate = {
  src: null,
  role: "13.0-14.0s. Appetite. One second, cut hard on a beat.",
  prompt:
    "Macro close-up of a freshly delivered Middle Eastern dinner being opened at home at night - " +
    "chicken shawarma, warm flatbread, mezze, visible steam rising off the food, crisp edges and " +
    "glistening texture. Hands out of frame. Warm overhead restaurant-style key light, deep shadows, " +
    "very shallow depth of field, slow creeping push in. " +
    `${LOOK} ${NO_TEXT}`,
  screen: null,
};

export const PLATES = { HOOK, REACTION, FOOD } as const;

/**
 * Audio.
 *
 * The music bed and the sound design are generated by scripts/build-ad-audio.mjs
 * and written into public/ad/, so they are reproducible, exactly on the 120bpm
 * grid the picture is cut to, and owned outright - no library, no licence to
 * check before this runs as a paid ad.
 *
 * The voiceover is not, and cannot be produced here. `vo.ts` holds the script
 * and the frame each line has to start on; drop the recorded lines in as
 * public/ad/vo/<id>.wav and they land where the picture expects them.
 */
export const AUDIO = {
  music: "ad/music-bed.wav" as string | null,
  /** Per-line voiceover, named by the ids in vo.ts. Null until recorded. */
  voiceDir: null as string | null,
} as const;
