-- All seven emirates in the area picker.
--
-- The product is advertised in Dubai and the comparison work is done there, but
-- an ad that works gets forwarded: somebody in Al Nahda tells their cousin in
-- Sharjah, and until now that cousin reached a dropdown with nowhere to put
-- themselves and left. Being listed is not a promise of coverage - a basket we
-- cannot price already has an honest answer, and "we couldn't find it" is a
-- better outcome than a form that cannot be completed.
--
-- city is the heading a customer sees, which is why Al Ain is its own group
-- rather than thirty entries buried inside Abu Dhabi - people there do not
-- think of themselves as living in Abu Dhabi. emirate stays legally true for
-- the same rows, so reporting by emirate keeps working.
--
-- Safe to re-run: (city, name) is unique and every insert ignores conflicts, so
-- this never touches an area an admin has since renamed, reordered or hidden.
--
-- Sort order is per group, not per row. Areas inside a group are ordered by
-- name, so adding one later needs no renumbering. Dubai keeps its existing
-- 10-470 and therefore stays at the top, where the customers still are.

insert into public.areas (name, city, emirate, active, sort_order) values
  ('Al Bahia', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Bateen', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Danah', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Falah', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Karamah', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Khalidiyah', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Manhal', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Maryah Island', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Mushrif', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Nahyan', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Raha Beach', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Raha Gardens', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Rahba', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Reef', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Reem Island', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Shamkha', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Wahdah', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Zahiyah', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Baniyas', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Between the Two Bridges', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Corniche', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Khalifa City', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Madinat Zayed', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Masdar City', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Mohammed Bin Zayed City', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Mussafah', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Ruwais', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Saadiyat Island', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Shakhbout City', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Yas Island', 'Abu Dhabi', 'Abu Dhabi', true, 1000),
  ('Al Asharej', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Al Bateen', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Al Foah', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Al Hili', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Al Jimi', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Al Khabisi', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Al Khrair', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Al Maqam', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Al Markhaniya', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Al Mutarad', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Al Mutawaa', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Al Muwaiji', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Al Sarooj', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Al Towayya', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Al Yahar', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Central District', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Falaj Hazzaa', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Neima', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Shiab Al Ashkhar', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Zakher', 'Al Ain', 'Abu Dhabi', true, 2000),
  ('Abu Shagara', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Azra', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Fisht', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Ghuwair', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Heerah', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Khan', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Layyah', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Mahatta', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Majaz', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Nahda', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Nasserya', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Nud', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Qasimia', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Qulayaa', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Rahmaniya', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Ramtha', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Sajaa', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Suyoh', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Taawun', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Tai', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Yarmook', 'Sharjah', 'Sharjah', true, 3000),
  ('Al Zahia', 'Sharjah', 'Sharjah', true, 3000),
  ('Barashi', 'Sharjah', 'Sharjah', true, 3000),
  ('Dibba Al-Hisn', 'Sharjah', 'Sharjah', true, 3000),
  ('Halwan', 'Sharjah', 'Sharjah', true, 3000),
  ('Hoshi', 'Sharjah', 'Sharjah', true, 3000),
  ('Kalba', 'Sharjah', 'Sharjah', true, 3000),
  ('Khorfakkan', 'Sharjah', 'Sharjah', true, 3000),
  ('Maysaloon', 'Sharjah', 'Sharjah', true, 3000),
  ('Muwaileh', 'Sharjah', 'Sharjah', true, 3000),
  ('Muwailih Commercial', 'Sharjah', 'Sharjah', true, 3000),
  ('Rolla', 'Sharjah', 'Sharjah', true, 3000),
  ('Samnan', 'Sharjah', 'Sharjah', true, 3000),
  ('Sharqan', 'Sharjah', 'Sharjah', true, 3000),
  ('Tilal City', 'Sharjah', 'Sharjah', true, 3000),
  ('University City', 'Sharjah', 'Sharjah', true, 3000),
  ('Ajman Corniche', 'Ajman', 'Ajman', true, 4000),
  ('Ajman Downtown', 'Ajman', 'Ajman', true, 4000),
  ('Al Alia', 'Ajman', 'Ajman', true, 4000),
  ('Al Bustan', 'Ajman', 'Ajman', true, 4000),
  ('Al Hamidiyah', 'Ajman', 'Ajman', true, 4000),
  ('Al Helio', 'Ajman', 'Ajman', true, 4000),
  ('Al Jurf', 'Ajman', 'Ajman', true, 4000),
  ('Al Mowaihat', 'Ajman', 'Ajman', true, 4000),
  ('Al Nuaimiya', 'Ajman', 'Ajman', true, 4000),
  ('Al Rashidiya', 'Ajman', 'Ajman', true, 4000),
  ('Al Rawda', 'Ajman', 'Ajman', true, 4000),
  ('Al Rumailah', 'Ajman', 'Ajman', true, 4000),
  ('Al Sawan', 'Ajman', 'Ajman', true, 4000),
  ('Al Tallah', 'Ajman', 'Ajman', true, 4000),
  ('Al Zahra', 'Ajman', 'Ajman', true, 4000),
  ('Emirates City', 'Ajman', 'Ajman', true, 4000),
  ('Garden City', 'Ajman', 'Ajman', true, 4000),
  ('Manama', 'Ajman', 'Ajman', true, 4000),
  ('Masfout', 'Ajman', 'Ajman', true, 4000),
  ('Al Dar Al Baida', 'Umm Al Quwain', 'Umm Al Quwain', true, 5000),
  ('Al Haditha', 'Umm Al Quwain', 'Umm Al Quwain', true, 5000),
  ('Al Humrah', 'Umm Al Quwain', 'Umm Al Quwain', true, 5000),
  ('Al Raas', 'Umm Al Quwain', 'Umm Al Quwain', true, 5000),
  ('Al Riqqah', 'Umm Al Quwain', 'Umm Al Quwain', true, 5000),
  ('Al Salamah', 'Umm Al Quwain', 'Umm Al Quwain', true, 5000),
  ('Falaj Al Mualla', 'Umm Al Quwain', 'Umm Al Quwain', true, 5000),
  ('Old Town', 'Umm Al Quwain', 'Umm Al Quwain', true, 5000),
  ('Umm Al Quwain Marina', 'Umm Al Quwain', 'Umm Al Quwain', true, 5000),
  ('Al Dhait', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Al Ghail', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Al Hamra Village', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Al Jazirah Al Hamra', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Al Mairid', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Al Marjan Island', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Al Nakheel', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Al Qusaidat', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Al Rams', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Al Turrah', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Al Uraibi', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Dafan Al Khor', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Dafan Al Nakheel', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Digdaga', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Julphar', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Khatt', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Khuzam', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Mina Al Arab', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('RAK Corniche', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Seih Al Uraibi', 'Ras Al Khaimah', 'Ras Al Khaimah', true, 6000),
  ('Al Aqah', 'Fujairah', 'Fujairah', true, 7000),
  ('Al Bidyah', 'Fujairah', 'Fujairah', true, 7000),
  ('Al Faseel', 'Fujairah', 'Fujairah', true, 7000),
  ('Al Gurfa', 'Fujairah', 'Fujairah', true, 7000),
  ('Al Hilal City', 'Fujairah', 'Fujairah', true, 7000),
  ('Al Taween', 'Fujairah', 'Fujairah', true, 7000),
  ('Dibba Al-Fujairah', 'Fujairah', 'Fujairah', true, 7000),
  ('Fujairah City', 'Fujairah', 'Fujairah', true, 7000),
  ('Madhab', 'Fujairah', 'Fujairah', true, 7000),
  ('Masafi', 'Fujairah', 'Fujairah', true, 7000),
  ('Merashid', 'Fujairah', 'Fujairah', true, 7000),
  ('Mirbah', 'Fujairah', 'Fujairah', true, 7000),
  ('Qidfa', 'Fujairah', 'Fujairah', true, 7000),
  ('Sakamkam', 'Fujairah', 'Fujairah', true, 7000)
on conflict (city, name) do nothing;
